version: '3.8'


services:
  web:
    build: .
    depends_on:
     - db
    command: /app/entrypoint.sh
    volumes:
     - static_data:/app/static
     - media_data:/app/media
    expose:
      - 8000
    env_file:
      - ./.env

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mindtify
      - POSTGRES_PASSWORD=mindtify
      - POSTGRES_DB=mindtify_db

  nginx:
    build: ./nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static/
      - media_data:/var/www/html/media/

volumes:
  static_data:
  media_data:
  postgres_data: