version: '3.8'


services:
  web:
    build: .
    command: gunicorn mindtify.wsgi:application --bind 0.0.0.0:8000
    volumes:
     - static_volume:/usr/src/app/static
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - web

volumes:
  static_volume: